name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_dotnet:
    name: Build and Deploy .NET Web API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Specify your .NET version

    - name: Build .NET Web API
      working-directory: ./EventManager.WebApi
      run: dotnet build --configuration Release

    - name: Publish .NET Web API
      run: dotnet publish --configuration Release EventManager.Webapi -o out 

    - name: Build Docker image for .NET Web API
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-webapi -f Dockerfile . 

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image for .NET Web API
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-webapi
