name: Build Docker images

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build_and_deploy_dotnet:
    name: Build and Deploy .NET Web API
    runs-on: ubuntu-latest
    env:
      YC_DOCKER_REGISTRY_URI: cr.yandex/crptg6nm3l5g6e4nn43a
      IMAGE_NAME: m1stym1st/dotnet-webapi
      YC_SERVERLESS_CONTAINER_NAME: api-events
      YC_SERVICE_ACCOUNT_ID: ajecnv18e2v9t936e40c
      YC_AUTHORIZED_KEY_JSON: ${{ secrets.YCKEY }}
      YC_FOLDER_ID: b1gts99os6kais5qm3ab
    defaults:
      run:
        working-directory: ./EventManager.WebApi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Specify your .NET version

    - name: Build .NET Web API
      run: dotnet build --configuration Release

    - name: Publish .NET Web API
      run: dotnet publish --configuration Release -o out 

    - name: Get Yandex Cloud IAM token
      id: get-iam-token
      uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
      with:
        yc-sa-id: $YC_SERVICE_ACCOUNT_ID

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: iam
        password: ${{ steps.get-iam-token.outputs.token }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CR_REGISTRY: crptg6nm3l5g6e4nn43a
        CR_REPOSITORY: m1stym1st
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

    - name: Deploy Serverless Container
      id: deploy-sls-container
      uses: yc-actions/yc-sls-container-deploy@v3
      with:
        yc-sa-id: $YC_SERVICE_ACCOUNT_ID
        container-name: $YC_SERVERLESS_CONTAINER_NAME
        folder-id: $YC_FOLDER_ID
        revision-service-account-id: $YC_SERVICE_ACCOUNT_ID
        revision-cores: 1
        revision-memory: 512Mb
        revision-core-fraction: 20
        revision-concurrency: 1
        revision-image-url: $YC_DOCKER_REGISTRY_URI/$IMAGE_NAME:${{ github.run_number }}
        revision-execution-timeout: 10
