name: Build Docker images

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build_and_deploy_dotnet:
    name: Build and Deploy .NET Web API
    runs-on: ubuntu-latest
    env:
      YC_DOCKER_REGISTRY_URI: cr.yandex/crphhtvgjecg3ue303sg
      IMAGE_NAME: m1stym1st/dotnet-webapi
      YC_SERVERLESS_CONTAINER_NAME: api-events
      YC_SERVICE_ACCOUNT_ID: ajecnv18e2v9t936e40c
      YC_AUTHORIZED_KEY_JSON: ${{ secrets.key }}
      YC_FOLDER_ID: b1gts99os6kais5qm3ab
    defaults:
      run:
        working-directory: ./EventManager.WebApi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Specify your .NET version

    - name: Build .NET Web API
      run: dotnet build --configuration Release

    - name: Publish .NET Web API
      run: dotnet publish --configuration Release -o out 

    - name: Install and configure Yandex Cloud CLI
      run: |
          # Install yc to local directory
          echo "Installing Yandex Cloud CLI..."
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/.yc -n
          echo "$HOME/.yc/bin" >> $GITHUB_PATH
    
          # Configure authentication using only the key
          echo "Configuring authentication..."
          KEY_FILE="$HOME/yandex_key.json"
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > $KEY_FILE
    
          # Automatically extract folder_id from the key
          FOLDER_ID=$(jq -r '.folder_id' $KEY_FILE)
    
          $HOME/.yc/bin/yc config set service-account-key $KEY_FILE
          $HOME/.yc/bin/yc config set folder-id $FOLDER_ID
    
          # Configure Docker
          echo "Configuring Docker registry access..."
          $HOME/.yc/bin/yc container registry configure-docker
    
          # Verify configuration
          echo "Verifying configuration..."
          $HOME/.yc/bin/yc config list
          $HOME/.yc/bin/yc container registry list
    
          # Cleanup
          rm -f $KEY_FILE
          echo "Setup completed successfully"
      
    - name: docker-login
      run: yc container registry configure-docker --profile sa-profile

    - name: docker-build-push
      run: |
          docker build --tag $YC_DOCKER_REGISTRY_URI/$IMAGE_NAME --platform linux/amd64 .
          docker push $YC_DOCKER_REGISTRY_URI/$IMAGE_NAME:latest
    
    - name: docker-logout
      run: docker logout $YC_DOCKER_REGISTRY_URI

    - name: create-serverless
      run: yc serverless container revision deploy  --container-name $YC_SERVERLESS_CONTAINER_NAME --image $YC_DOCKER_REGISTRY_URI/$IMAGE_NAME:latest --service-account-id $YC_SERVICE_ACCOUNT_ID
