name: Build Docker images

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build_and_deploy_dotnet:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Build and Deploy .NET Web API
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: m1stym1st/dotnet-webapi
      YC_AUTHORIZED_KEY_JSON: ${{ secrets.YCKEY }}
    defaults:
      run:
        working-directory: ./EventManager.WebApi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Specify your .NET version

    - name: IAM Token
      id: issue-iam-token
      uses: yc-actions/yc-iam-token@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YCKEY }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: iam
        password: ${{ steps.issue-iam-token.outputs.token }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        CR_REGISTRY: crptg6nm3l5g6e4nn43a
        CR_REPOSITORY: m1stym1st
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

    - name: Deploy Serverless Container
      id: deploy-sls-container
      uses: yc-actions/yc-sls-container-deploy@v3
      with:
        yc-iam-token: ${{ steps.issue-iam-token.outputs.token }}
        container-name: api-events
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        revision-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        revision-cores: 1
        revision-memory: 512Mb
        revision-core-fraction: 20
        revision-concurrency: 1
        revision-image-url: ${{ secrets.YC_DOCKER_REGISTRY_URI }}/api-events:${{ github.run_number }}
        revision-execution-timeout: 10
